import { LayoutForNewsPost } from '@/components/common/LayoutForNewsPost'
import { useGetNewsPostByIdQuery } from 'generated/types-and-hooks'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import ReactMarkdown from 'react-markdown'

const NewsPost = () => {
  const router = useRouter()
  const { id } = router.query

  const { data, loading } = useGetNewsPostByIdQuery({
    variables: {
      id: id as string,
    },
  })

  if (loading) return <div>Loading....</div>

  const news = data?.newspost?.data?.attributes

  return (
    <>
      <Head>
        <title>Title</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='col-start-2 col-end-3 pt-8 bg-white dark:bg-gray-900'>
        <div className='flex justify-between px-4 mx-auto max-w-screen-xl '>
          <article className='mx-auto w-full max-w-2xl format format-sm sm:format-base lg:format-lg format-blue dark:format-invert'>
            <header className='mb-4 lg:mb-6 not-format'>
              <address className='flex items-center mb-6 not-italic'>
                <div className='inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white'>
                  {/* <img className="mr-4 w-16 h-16 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-2.jpg" alt="Jese Leos" /> */}
                  <div>
                    <p className='text-xl font-bold text-gray-900 dark:text-white'>
                      {news?.writtenBy}
                    </p>
                    <p className='text-base font-light text-gray-500 dark:text-gray-400'>
                      <time dateTime='2022-02-08' title='February 8th, 2022'>
                        Feb. 8, 2022
                      </time>
                    </p>
                  </div>
                </div>
              </address>
              <h1 className='mb-4 text-3xl font-extrabold leading-tight text-gray-900 lg:mb-6 lg:text-4xl dark:text-white'>
                {news?.title}
              </h1>
            </header>
            <img src={news?.imageUrl} alt={news?.slug} />
            <ReactMarkdown children={news?.body || ''} />
            <section className='not-format'>
              <div className='flex justify-between items-center mb-6'>
                <h2 className='text-lg lg:text-2xl font-bold text-gray-900 dark:text-white'>
                  Discussion (20)
                </h2>
              </div>
            </section>
          </article>
        </div>
      </main>
    </>
  )
}

export default NewsPost

NewsPost.getLayout = function getLayout(page: React.ReactElement) {
  return <LayoutForNewsPost>{page}</LayoutForNewsPost>
}
