import Head from 'next/head'
import { useRouter } from 'next/router';
import React from 'react'

const NewsPost = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Title</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>HELLO</div>
    </>
  )
}

export default NewsPost